### ISSUE TITLE
flui的计划

### ISSUE THREAD

**Issue by 986244073** [Rannie/flui#10]
想知道接下来会开发那些组件  和  功能 
建议建个群

**Comment by Rannie** [comment]
> 想知道接下来会开发那些组件 和 功能
> 建议建个群

@986244073  下个版本会聚焦在继续添加组件以及完善文档上，1.0 版本会有些“新”的功能加进来。
因为用户还不是很多，沟通可以先通过 issue ，暂时没有建群的计划...
