### ISSUE TITLE
close toast callback

### ISSUE THREAD

**Issue by shuck** [Rannie/flui#11]
need callback

**Comment by Rannie** [comment]
> need callback

ok, will add it.

**Comment by AstrayV** [comment]
有时出现的情况就是，close后面跟着一个 navigator.pop(), toast就没有关掉。

**Comment by Rannie** [comment]
> 有时出现的情况就是，close后面跟着一个 navigator.pop(), toast就没有关掉。

@AstrayV 是偶尔出现不是必现吗？ 方便的话可以把相关的 flutter doctor 信息和代码贴过来

**Comment by AstrayV** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G95, locale zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2018.1.7)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.41.1)
[!] Connected device
    ! No devices available

没有callback是会存在偶现的关不掉的，之前用cool ui 的 loading toast 也存在这个问题.

**Comment by Rannie** [comment]
@AstrayV 这个信息还是太少了，有什么 demo 代码之类的吗，或者你 debug 发现的问题。
另外，有没有 callback 跟关闭的逻辑没有关联

**Comment by Rannie** [comment]
0.9.0 added
