### ISSUE TITLE
Use FLToast to report an error

### ISSUE THREAD

**Issue by 370966584** [Rannie/flui#12]
![image](https://user-images.githubusercontent.com/26058251/71649718-ea01b900-2d4b-11ea-9cef-7b9f200a9c69.png)
 
flutter 1.9.1+hotfix.6
flui 0.7.4

**Comment by Rannie** [comment]
You should add FLToastProvider in your widget tree. 
https://www.flui.xin/en/widgets/toast.html#fltoastprovider
Duplicate of #4

**Comment by 370966584** [comment]
> 您应该在窗口小部件树中添加FLToastProvider。
> https://www.flui.xin/en/widgets/toast.html#fltoastprovider
> 的重复[＃4](https://github.com/Rannie/flui/issues/4)
多谢，抱歉，没有仔细看文档
