### ISSUE TITLE
Add “Why this” to README

### ISSUE THREAD

**Issue by gisborne** [Rannie/flui#16]
There is nothing in the README to indicate why I might choose this over the standard widgets. Please add a paragraph near the top of the README about why I might want to use this project.

**Comment by Rannie** [comment]
Hi @gisborne , this is just an extension of the basic widgets. 
If you have a scenario that requires these widgets, you can choose FLUI.

**Comment by gisborne** [comment]
Well, sure. But someone coming to this as I did is going to ask themselves “How are these widgets different from the standard ones.” When there is no information about that, how would I know if in your words, my “scenario requires these widgets”.
