### ISSUE TITLE
FLMarqueeLabel建议扩展增加左右图标和点击事件

### ISSUE THREAD

**Issue by fg2q1q3q** [Rannie/flui#19]
目前的实现如果想加图标会非常不方便，建议flui直接扩展该功能，或者将slaveTextChild交由开发者自己处理，而不是目前固定成Text，局限性很大

**Comment by Rannie** [comment]
@fg2q1q3q ok 这个会扩展

**Comment by fg2q1q3q** [comment]
不好意思，我发现noticeBar有这个功能（只是不能更换图标），在使用noticeBar过程中发现一处bug，设置backgroundColor的时候会报错Color类型不能为bool类型，经查应该是如下代码中少了一个括号导致：
···
Color barBackgroundColor = backgroundColor ?? isDarkMode
        ? accent.withOpacity(0.2)
        : FLNoticeBarBackgroundColor;
···

**Comment by Rannie** [comment]
@fg2q1q3q 这个问题我会跟一下，左右侧 Icon 的问题 noticebar 支持自定义的 prefixBuilder 和 suffixBuilder 的，你可以尝试下，文档我会在下个版本 1.0 尽量补充全

**Comment by Rannie** [comment]
0.9.0 fixed
