### ISSUE TITLE
提个小建议, 东西不太多,有的还有bug 比如toast

### ISSUE THREAD

**Issue by lalaMiao** [Rannie/flui#21]
toast ,dissMiss 反人类. 而且还有bug  loading 立马dismiss 不消失

**Comment by lalaMiao** [comment]
hideWithTap,  这个属性, 貌似没卵用

**Comment by Rannie** [comment]
@lalaMiao 
1. dismiss 的方式参考自 ant-design, 如果你有更好的方式可以提出你的建议或者 pr 而不只是说'反人类'
2. bug 请提供上下文，'立马 dismiss' 这句话没卵用
3. hideWithTap 默认是开启的，显示普通 toast 时点击区域会隐藏 toast

我主要关注你说的 bug 部分，请给出详细信息

**Comment by Rannie** [comment]
另外如果你是 dismiss 函数生成后立即调用的话，那肯定不会消失，因为那个时候只是 insertEntry， 还并没有渲染。请在需要 loading 的场景下再调用 =p
