### ISSUE TITLE
FLCupertinoOperationSheet设置backgroundColor无效

### ISSUE THREAD

**Issue by leyi422** [Rannie/flui#24]
FLCupertinoOperationSheet设置backgroundColor无效

**Comment by leyi422** [comment]
话说这个库还在维护吗

**Comment by Rannie** [comment]
@leyi422 在维护的，最近比较忙。。

**Comment by leyi422** [comment]
﻿辛苦

发自我的iPhone

在 2020年4月9日，17:00，Hanran Liu <notifications@github.com> 写道：

﻿

@leyi422<https://github.com/leyi422> 在维护的，最近比较忙。。

**Comment by Rannie** [comment]
@leyi422 0.9.1 fix, 久等了
