### ISSUE TITLE
FLGradientLoadingButton

### ISSUE THREAD

**Issue by wangbo4020** [Rannie/flui#26]
能否支持以下按钮
```
FLLoadingButton.liner
FLLoadingButton.radial
FLLoadingButton.sweep
```
or
```
FLGradientButton(loading: true)
```

**Comment by Rannie** [comment]
Hi @wangbo4020  其实现在 loading 按钮的设计是稍微偷懒的结果，因为 loading 的样式固定使用 CircularProgressIndicator，strokeWidth 也是固定的，实现上并不复杂。可能暂时不会再对 gradient button 增加相同的设计，你可以自己在其 child 上做一些功夫来添加 loading 。
感谢。
