### ISSUE TITLE
动态配色建议

### ISSUE THREAD

**Issue by YeungKC** [Rannie/flui#28]
由于现在很多时候需要实现明亮和暗黑模式，而两者的要求色彩不同，对比度不同，很难切换，是否可以做一个动态配色？
我见过比较完善的方案是 https://github.com/adobe/leonardo，色彩比较专业，感觉如果用这个就很不错～

**Comment by Rannie** [comment]
hi @YeungKC,
其实 flui 不会做很多风格化或者配色方面的尝试，因为 flutter 对于主题支持已经很到位而色彩搭配又因为 toc 的 app 一般会有专业的设计来做，所以使用上可以参照模板来填充颜色，具体的颜色如何选择框架则不会参与。
感谢你的建议~
