### ISSUE TITLE
[input] long press the input widget will crash

### ISSUE THREAD

**Issue by JellyHell** [Rannie/flui#29]
## step
1.run the flui demo
2.open the Input page
3.long press the input widget will crash

## flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Android Studio (version 3.6)
[✓] Connected device (2 available)
• No issues found!

## crash info
![WechatIMG37](https://user-images.githubusercontent.com/4350951/81366470-54bd6980-911d-11ea-9450-04b5b76bdd0c.jpeg)

**Comment by Rannie** [comment]
thanks, i will start to focus on this issue in the next few days.

**Comment by Rannie** [comment]
hi @JellyHell, i changed the usage of FLToastProvider and fix it now. 
thanks.

**Comment by JellyHell** [comment]
Thanks
