### ISSUE TITLE
使用 Toast 导致 文本框双击就报错

### ISSUE THREAD

**Issue by Exclusive-gfj** [Rannie/flui#32]
环境：
     flutter SDK - 1.17.0
     flui: ^0.9.1

错误

The following assertion was thrown building _OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#802fc](dirty, state: _OverlayEntryWidgetState#171e5):
No MediaQuery widget found.

_OverlayEntryWidget widgets require a MediaQuery widget ancestor.
The specific widget that could not find a MediaQuery ancestor was: _OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#802fc]
  dirty
  state: _OverlayEntryWidgetState#171e5
The ownership chain for the affected widget is: "_OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#802fc] ← _Theatre ← Overlay ← Stack ← Directionality ← _FLToastDefaultsWidget ← FLToastProvider ← MyApp ← _InheritedProviderScope<StoreProvider> ← ChangeNotifierProvider<StoreProvider> ← ⋯"

Typically, the MediaQuery widget is introduced by the MaterialApp or WidgetsApp widget at the top of your application widget tree.

**Comment by Rannie** [comment]
ok 我这边跟进下

**Comment by Rannie** [comment]
hi @Exclusive-gfj , 我这边修改了 FLToastProvider 的使用方式 https://www.flui.xin/widgets/toast.html#fltoastdefaults，感谢指出~
