### ISSUE TITLE
Flutter版本 1.12.13+hotfix.8运行报错

### ISSUE THREAD

**Issue by TinySungo** [Rannie/flui#34]
Flutter版本 1.12.13+hotfix.8
运行报错

**Comment by TinySungo** [comment]
Flutter版本 1.12.13+hotfix.8
如何解决一下报错？

Compiler message:
../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/flui-0.9.2/lib/src/widgets/persistent_header.dart:117:11: Error: Superclass has no method named 'forgetChild'.
    super.forgetChild(child);
          ^^^^^^^^^^^
../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/flui-0.9.2/lib/src/widgets/persistent_header.dart:199:11: Error: Superclass has no method named 'forgetChild'.
    super.forgetChild(child);
          ^^^^^^^^^^^

**Comment by TinySungo** [comment]
注释掉 super.forgetChild(child);  解决了

**Comment by Rannie** [comment]
@TinySungo ，嗯 Flutter v1.17 起要 call super 了，如果是之前版本你可以注释掉
