### ISSUE TITLE
关于文档的问题

### ISSUE THREAD

**Issue by Jokky6** [Rannie/flui#8]
个人认为现在的组件文档的api列表都没有，这是一个很糟糕的文档，能否花出一些宝贵时间，整理一下各个组件的api列表呢？
可以以element-ui、ant-design的api列表为例哦！现在组件库没有api列表，真的仅此一家了！

**Comment by Rannie** [comment]
> 个人认为现在的组件文档的api列表都没有，这是一个很糟糕的文档，能否花出一些宝贵时间，整理一下各个组件的api列表呢？
> 可以以element-ui、ant-design的api列表为例哦！现在组件库没有api列表，真的仅此一家了！

这个在 0.9 版本的范围内的，因为一开始设计的时候考虑到 flutter 发展比较快，先专注于组件设计和实现了，api 稳定一点后补充进来。
0.9 版本每个组件文档页底部会有 api table 的。

**Comment by Jokky6** [comment]
嗯嗯，这个api table一定要认真定，这个一旦定了就尽量不要再改了。

**Comment by Jokky6** [comment]
好的哦。

**Comment by Rannie** [comment]
API  文档已经添加，并且会逐步完善。
